# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 415073fde184a81060484fa2dc466bbb38d34e1d58fa89752bd827d1a3095746d36a9584576504704402f89eea50426ff5316e7f5961cac4e503199ac116e4c3

test:
  secret_key_base: 47bb9ddb904451bda32726443a4351f7ab47589225c41d8850a51402ed454749be1a6e78f9d48480ec8add213505e3f189bd119c748ff7220d2e5c9772b1050f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
